### PR TITLE
fix(rustup): Correct template issues

### PR DESCRIPTION
**Pull request by epage**

### CODE REVIEW

**Comment by nickbabcock** [comment]
Why remove the conditional inserts for `rustup.yml` based on agent os?

**Comment by epage** [comment]
So why switch from conditional inserts to `condition:`?  For some reason, `variables["Agent.OS"]` was not available when conditional insertion was being evaluated.  It evaluated to "" and made all OS run the non-Windows version of the step.  If you have ideas on how to fix that, feel free to create a PR to experiment with it.

**Comment by nickbabcock** [comment]
>  For some reason, variables["Agent.OS"] was not available when conditional insertion was being evaluated

Weird, I don't think I've noticed that, but some behavior seems flaky. I'll experiment tomorrow 😄

**Comment by epage** [comment]
Some might be flaky, some I feel is jut so poorly documented that people can't create a proper mental model around it so it feels flaky :)

btw using `condition:` is actually what they recommend in the docs (found after debugging this for hours)
https://docs.microsoft.com/en-us/azure/devops/pipelines/scripts/cross-platform-scripting?view=azure-devops&tabs=yaml#switch-based-on-platform

**Comment by nickbabcock** [comment]
I feel like they are recommending conditions over conditional inserts in templates for those who haven't written templates. I don't see the benefit of conditions in this case, as they leave a skipped step. Now, one skipped step in a pipeline isn't bad, but if each template used in a build contains skipped steps -- this could lead to a pollution of skipped steps.

**Comment by nickbabcock** [comment]
My apologies, maybe at one point `Agent.OS` worked, it is no longer part of variables at template compile time. I printed them all out with:

```yaml
steps:
 - ${{ each pair in variables }}:
   - script: echo ${{ pair.key }} ${{ pair.value }}
     displayName: ${{ pair.key }} ${{ pair.value }}
```

And nothing was related to the OS

**Pull request merged**
